name: Build Nix flake
on:
  push:

jobs:
  build:
    name: Build Nix flake
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      # Clear space for Nix
      # - uses: wimpysworld/nothing-but-nix@main

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Build Nix flake
        run: |
          nix build .#devShells.x86_64-linux.default
