name: Build Nix flake
on:
  push:

jobs:
  build:
    name: Build Nix flake
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Clear space for Nix
      # - uses: wimpysworld/nothing-but-nix@main

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@main

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15

      - name: Build Nix flake
        run: |
          nix build .#devShells.x86_64-linux.default
